version: '3'
services:
  database:
    build:
      context: ./database
      args:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
          - "${MYSQL_PORT}:3306" #For Local Development
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
  backend:
    build: ./partial-api
    ports:
      - "5001:80"
    restart: always
    volumes:
      - ~/logs/:/usr/src/app/logs/
    links:
      - database
    depends_on:
      - database
  #frontend:
  #  build: ./partial-www/
  #  ports:
  #   - "5002:80"
  #  links:
  #    - backend
  #  restart: always
  